export const mockResponses = [
    {
        id: '1',
        name: 'John Doe',
        email: 'john.doe@example.com',
        phone: '123-456-7890',
        faculty: 'Engineering',
        yearOfStudy: '3',
        overallSatisfaction: 'Very Satisfied',
        campusFacilities: 'Excellent',
        teachingQuality: 'Good',
        campusLife: 'Excellent',
        recommend: 'Yes',
        additionalFeedback: 'The new library is a fantastic addition!',
        submissionDate: '2024-10-28',
    },
    {
        id: '2',
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '234-567-8901',
        faculty: 'Arts & Science',
        yearOfStudy: '2',
        overallSatisfaction: 'Satisfied',
        campusFacilities: 'Good',
        teachingQuality: 'Excellent',
        campusLife: 'Good',
        recommend: 'Yes',
        additionalFeedback: 'More vegetarian options in the cafeteria would be great.',
        submissionDate: '2024-10-27',
    },
    {
        id: '3',
        name: 'Peter Jones',
        email: 'peter.jones@example.com',
        phone: '345-678-9012',
        faculty: 'Business',
        yearOfStudy: '4',
        overallSatisfaction: 'Neutral',
        campusFacilities: 'Average',
        teachingQuality: 'Good',
        campusLife: 'Average',
        recommend: 'Maybe',
        additionalFeedback: '',
        submissionDate: '2024-10-26',
    },
    {
        id: '4',
        name: 'Mary Williams',
        email: 'mary.williams@example.com',
        phone: '456-789-0123',
        faculty: 'Medicine',
        yearOfStudy: '1',
        overallSatisfaction: 'Dissatisfied',
        campusFacilities: 'Poor',
        teachingQuality: 'Average',
        campusLife: 'Poor',
        recommend: 'No',
        additionalFeedback: 'The registration process was very confusing.',
        submissionDate: '2024-10-25',
    },
    {
        id: '5',
        name: 'David Brown',
        email: 'david.brown@example.com',
        phone: '567-890-1234',
        faculty: 'Engineering',
        yearOfStudy: '3',
        overallSatisfaction: 'Satisfied',
        campusFacilities: 'Good',
        teachingQuality: 'Good',
        campusLife: 'Good',
        recommend: 'Yes',
        additionalFeedback: '',
        submissionDate: '2024-10-24',
    },
    {
        id: '6',
        name: 'Susan Miller',
        email: 'susan.miller@example.com',
        phone: '678-901-2345',
        faculty: 'Arts & Science',
        yearOfStudy: '2',
        overallSatisfaction: 'Very Satisfied',
        campusFacilities: 'Excellent',
        teachingQuality: 'Excellent',
        campusLife: 'Excellent',
        recommend: 'Yes',
        additionalFeedback: 'The professors in my department are very supportive.',
        submissionDate: '2024-10-23',
    },
];
